# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJebW9NdhyuDHTptic7yNkfr8AyQYMGQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import csv


FILE_NAME = 'expenses.csv'





def log_expense():
        category = input("Enter the category : ")
        amount =int(input("Enter the amount : "))
        date =input("Enter the date : ")
        try:
            file=open(FILE_NAME,'r')
            file.close()
        except:
            file=open(FILE_NAME,mode='w',newline='')
            writer=csv.writer(file)
            writer.writerow(["category","amount","date"])
            file.close()
        row=[category,amount,date]
        file=open(FILE_NAME,'a')
        writer=csv.writer(file)
        writer.writerow(row)
        file.close()


def Analyse_data():
        data =pd.read_csv(FILE_NAME)
        sum=0
        for i in data["amount"]:
            sum=sum+i
        print("Total = ",sum)


def Visualise_data():
    data= pd.read_csv(FILE_NAME)

    show=data.groupby("category")["amount"].sum()
    show.plot(kind="bar", figsize=(8, 6), title="Expenses by Category")
    plt.xlabel("Category")
    plt.ylabel("Total Amount")
    plt.show()

    show1=data.groupby("date")["amount"].sum()
    show1.plot(kind="bar", figsize=(8, 6), title="Expenses by date")
    plt.xlabel("date")
    plt.ylabel("Total Amount")
    plt.show()

while True:
    print("1 - Log Expense \n 2 - Analyse data \n 3 - Visualise Data \n 4 - EXIT")
    choice = int(input("Enter Your choice"))
    if choice == 1:
        log_expense()
    elif choice == 2:
        Analyse_data()
    elif choice == 3:
        Visualise_data()
    else:
        break